//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppStoreEntities : DbContext
    {
        public AppStoreEntities()
            : base("name=AppStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> action { get; set; }
        public virtual DbSet<application> application { get; set; }
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<environment> environment { get; set; }
        public virtual DbSet<i18n> i18n { get; set; }
        public virtual DbSet<icon> icon { get; set; }
        public virtual DbSet<mobile_crash> mobile_crash { get; set; }
        public virtual DbSet<privacy> privacy { get; set; }
        public virtual DbSet<release> release { get; set; }
        public virtual DbSet<tracking> tracking { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_application> user_application { get; set; }
        public virtual DbSet<user_application_role> user_application_role { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<i18n_data> i18n_data { get; set; }
    }
}
