//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
    	partial void Initialize();
        public int id { get; set; }
        public int application_id { get; set; }
        public string environment_type { get; set; }
        public string device_type { get; set; }
        public string device_id { get; set; }
        public string user_id { get; set; }
        public string action_id { get; set; }
        public string param { get; set; }
        public string detail { get; set; }
        public long time_stamp { get; set; }
    
        public virtual application application { get; set; }
        public virtual device device { get; set; }
        public virtual environment environment { get; set; }
    }
}
